name: Lint and Build Presentation

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get install -y chktex texlive-latex-extra

      - name: Lint presentation.tex
        run: make test

      - name: Build presentation.tex
        run: make all

      - name: Publish presentation
        uses: ncipollo/release-action@v1
        with:
          artifacts: "presentation.pdf"
          token: ${{ secrets.GITHUB_TOKEN }}
