name: Lint and Build Presentation

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: lint presentation.tex
        run: make test

      - name: build presentation.tex
        run: make all
